insert into user_tb(username, password, email) values('ssar', '$2a$10$RTgIQccXXEPJo9zXdOMolOcs04UDc4wUHMIph3zgcUWmeQmTBbefW', 'ssar@nate.com');
insert into user_tb(username, password, email) values('cos', '$2a$10$RTgIQccXXEPJo9zXdOMolOcs04UDc4wUHMIph3zgcUWmeQmTBbefW', 'cos@nate.com');
insert into board_tb(title, content, user_id, created_at) values('제목1', '내용1', 1, now());
insert into board_tb(title, content, user_id, created_at) values('12', '내용2', 1, now());
insert into board_tb(title, content, user_id, created_at) values('cos', '내용3', 1, now());
insert into board_tb(title, content, user_id, created_at) values('ssar', '내용4', 2, now());
insert into board_tb(title, content, user_id, created_at) values('15', '내용5', 2, now());
insert into board_tb(title, content, user_id, created_at) values('16', '내용6', 2, now());
insert into board_tb(title, content, user_id, created_at) values('17', '내용7', 2, now());
insert into board_tb(title, content, user_id, created_at) values('제목8', '내용8', 2, now());
insert into reply_tb(comment, board_id, user_id) values('댓글1', '1', 1);
insert into reply_tb(comment, board_id, user_id) values('댓글2', '1', 1);
insert into reply_tb(comment, board_id, user_id) values('댓글3', '1', 2);
insert into reply_tb(comment, board_id, user_id) values('댓글4', '1', 2);
insert into reply_tb(comment, board_id, user_id) values('댓글5', '1', 2);