insert into user_tb(username, password, email) values('ssar', '1234', 'ssar@nate.com');
insert into user_tb(username, password, email) values('cos', '1234', 'cos@nate.com');
insert into board_tb(title, content, user_id, created_at) values('제목1', '내용1', 1, now());
insert into board_tb(title, content, user_id, created_at) values('제목2', '내용2', 1, now());
insert into board_tb(title, content, user_id, created_at) values('제목3', '내용3', 1, now());
insert into board_tb(title, content, user_id, created_at) values('제목4', '내용4', 2, now());
insert into board_tb(title, content, user_id, created_at) values('제목5', '내용5', 2, now());
insert into board_tb(title, content, user_id, created_at) values('제목6', '내용6', 2, now());
insert into board_tb(title, content, user_id, created_at) values('제목7', '내용7', 2, now());
insert into board_tb(title, content, user_id, created_at) values('제목8', '내용8', 2, now());
insert into board_tb(title, content, user_id, created_at) values('제목9', '내용9', 2, now());
insert into board_tb(title, content, user_id, created_at) values('제목10', '내용10', 2, now());
insert into board_tb(title, content, user_id, created_at) values('제목11', '내용11', 2, now());
insert into board_tb(title, content, user_id, created_at) values('제목12', '내용12', 2, now());
insert into board_tb(title, content, user_id, created_at) values('제목13', '내용13', 2, now());
insert into board_tb(title, content, user_id, created_at) values('제목14', '내용14', 2, now());
insert into board_tb(title, content, user_id, created_at) values('제목15', '내용15', 2, now());