server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
spring:
  mustache:
    servlet:
      expose-session-attributes: true
      expose-request-attributes: true 
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  sql:
    init:
      data-locations:
      - classpath:db/data.sql # classpath:resources폴더 # 더미데이터 추가하려면 1
  jpa:
    defer-datasource-initialization: true # 더미데이터 추가하려면2
    hibernate:
      ddl-auto: create  # create 하면 db table 매번 새로만듬   /   update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
  output:
    ansi:
      enabled: always